import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import { SessionProvider } from "./auth/SessionProvider";
import { EntryModeProvider } from "./context/EntryModeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <Suspense fallback={null}>
          <EntryModeProvider>
            <SessionProvider>{children}</SessionProvider>
          </EntryModeProvider>
        </Suspense>
      </body>
    </html>
  );
}
